name: EPG Script Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run script
        run: |
          python epg_script.py
      - name: Create epgs folder
        run: |
          mkdir -p epgs
      - name: Move output files to epgs folder
        run: |
          mv epg.xml epgs/
          mv epg.xml.gz epgs/
      - name: Commit output files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add epgs/
          git commit -m "Update epgs folder" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
