---
name: daddylive-channels
save_as_gz: true
output_dir: epgs
tvg_ids_file: daddylive-channels-tvg-ids.txt
output_file: epgs/daddylive-channels-epg.xml
output_file_gz: epgs/daddylive-channels-epg.xml.gz
urls:
  - http://m3u4u.com/xml/5g28nezee8sv3dk7yzpe
  - https://epgshare01.online/epgshare01/epg_ripper_AR1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_AU1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_BEIN1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_BG1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_BR1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_CA1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_CL1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_CO1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_CR1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_CY1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_DE1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_DK1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_ES1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_FANDUEL1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_FR1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_GR1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_HR1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_IL1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_IN4.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_IT1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_MX1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_MY1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_NL1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_NZ1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_PK1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_PL1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_PT1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_RO1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_RO2.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_SA1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_SE1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_TR1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_UK1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_US1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_US_LOCALS2.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_UY1.xml.gz
  - https://epgshare01.online/epgshare01/epg_ripper_ZA1.xml.gz
