name: EPG Script Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run script
        run: |
          python epg_script.py
      - name: Upload output file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: epg_output
          path: epg.xml
      - name: Upload gzipped output file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: epg_output_gz
          path: epg.xml.gz
