name: EPG Script Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run script
        run: |
          python epg_script.py
      - name: Create epgs folder
        run: |
          mkdir -p epgs
      - name: Move output files to epgs folder
        run: |
          mv epg.xml epgs/
          mv epg.xml.gz epgs/
      - name: Commit output files
        run: |
          git config --local user
